version: '2'

services:

### Workspace Utilities Container ###########################

    lemp:
        build:
            context: ./
#            args:
#        volumes_from:
#           - voluems_data
        volumes:
           - ./sites:/etc/nginx/sites-enabled 
           - ./html:/usr/share/nginx/html
           - ./mongodb:/var/lib/mongodb
#        extra_hosts:
        ports:
           - "80:80"
           - "8000:8000"
           - "50022:22"
           - "27017:27017"
        tty: true
#        restart: always

### Databases Data Container ################################

#    volumes_data:
#        image: tianon/true
#        volumes:
#            - ./data/mysql:/var/lib/mysql
#            - ./data/mongo:/data/db
